### ISSUE TITLE
Skip building of Java/C++ bindings

### ISSUE THREAD

**Issue by ondrej-fabry** [contiv/docker-vpp#3]
Time it takes to compile VPP can be reduced by skipping build of unused parts, especially Java/C++ bindings.

This is done using argument in make call:
```sh
$ make vpp_configure_args_vpp='--disable-japi --disable-vom' pkg-deb...
```

**Comment by tiewei** [comment]
Added `UNATTENDED=y vpp_configure_args_vpp='--disable-japi --disable-vom --disable-papi' make install-dep bootstrap pkg-deb` it doesn't seem skipping build the package and i don't see `platforms.mk` has flag turn off the pkg building process.

some logs
```
dpkg-deb: building package 'vpp' in '../vpp_18.04-rc0~33-gb59bd65_amd64.deb'.
dpkg-deb: building package 'vpp-dbg' in '../vpp-dbg_18.04-rc0~33-gb59bd65_amd64.deb'.
dpkg-deb: building package 'vpp-dev' in '../vpp-dev_18.04-rc0~33-gb59bd65_amd64.deb'.
dpkg-deb: building package 'vpp-lib' in '../vpp-lib_18.04-rc0~33-gb59bd65_amd64.deb'.
dpkg-deb: building package 'vpp-plugins' in '../vpp-plugins_18.04-rc0~33-gb59bd65_amd64.deb'.
dpkg-deb: building package 'vpp-api-lua' in '../vpp-api-lua_18.04-rc0~33-gb59bd65_amd64.deb'.
dpkg-deb: building package 'vpp-api-java' in '../vpp-api-java_18.04-rc0~33-gb59bd65_amd64.deb'.
dpkg-deb: building package 'vpp-api-python' in '../vpp-api-python_18.04-rc0~33-gb59bd65_amd64.deb'.
```

**Comment by ondrajz** [comment]
You find the flag inside here: https://github.com/FDio/vpp/blob/master/build-data/platforms/vpp.mk

Did the overall time of the build decreased? We are using it this way in ligato/vpp-agent and we managed to decreased it by over 13 minutes.

**Comment by tiewei** [comment]
are you running the same make targets as i did ? I didn't see any time saving in my case, it's ~24min to run all the steps with or without the `vpp_configure_args_vpp` config,

**Comment by ondrej-fabry** [comment]
We started using it this way in our dev image: https://github.com/ligato/vpp-agent/blob/pantheon-dev/docker/dev_vpp_agent/Dockerfile#L33

You can see the drop in build time here:

![capture](https://user-images.githubusercontent.com/32484950/35507224-552e6c9e-04ec-11e8-9400-8cd3aaa999e0.PNG)

**Comment by unclejack** [comment]
It took 19 minutes to build without that option and 15 to build with it. I haven't built it multiple times to rule out noise.

The debian packages are still built.

**Comment by unclejack** [comment]
The `install-deb` target still builds all the deb packages when that environment variable is provided.

https://github.com/FDio/vpp/blob/master/build-data/platforms.mk#L58

**Comment by tiewei** [comment]
@ondrej-fabry are you compile it in container or just the same node ? I can try more times but the deb package would be built no matter what, could you fix it in vpp side if you were developing on that side? or where could we open issue for it

**Comment by ondrej-fabry** [comment]
The deb package are still being built for us as well. Not sure if that really increases compile by a lot though. And if you are at 15 minutes already that seems pretty good, but if you want you might create Jira issue for VPP guys here: https://jira.fd.io/browse/VPP

**Comment by tiewei** [comment]
I created a PR for this at https://github.com/contiv/docker-vpp/pull/5 . although i doubt if it will saves time, I'll run a few round if tests to see if it helps

**Comment by ondrej-fabry** [comment]
Maybe the time difference of compilation is more obvious at slower machine, as in my example which was run on some Jenkins worker.

**Comment by tiewei** [comment]
addressed in #7

**Comment by tiewei** [comment]
This change has been reverted due to the issue that the `vpp-api/client/vppapiclient.h` will not be included within vpp-dev.deb, this will cause vpp-agent compile error
https://github.com/contiv/docker-vpp/pull/11

**Comment by ondrej-fabry** [comment]
Did you try removing only one of those? Just Java and C++ for example.

**Comment by ondrej-fabry** [comment]
It's probably because you added `--disable-papi` and [we use it without disabling it](https://github.com/ligato/vpp-agent/blob/pantheon-dev/docker/dev_vpp_agent/Dockerfile#L33), just like in my OP.
